### ISSUE TITLE
That tool looks good. Is this project still in work?

### ISSUE THREAD

**Issue by Salamimonster** [tsasioglu/Keyboard-Tester#1]

**Comment by tsasioglu** [comment]
It's a thing I made for fun a few years ago but it still runs in windows 10, VS2019 etc. yes

**Comment by tsasioglu** [comment]
Exe @ https://github.com/tsasioglu/Keyboard-Tester/blob/master/KeyboardTester/bin/KeyboardTester.exe

**Comment by Salamimonster** [comment]
That was quick. :-)

Thank you for sharing.
